# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# NOTE: This workflow is maintained in the https://github.com/bitnami/support repository
name: '[Automation] Close solved issues'
on:
  schedule:
    # Hourly
    - cron: '0 * * * *'
permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'sommerit' }}
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f
        with:
          any-of-labels: 'solved'
          stale-issue-label: 'solved'
          days-before-stale: 0
          days-before-close: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
