# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# Native GitHub workflow configuration
name: '[Automation] Close solved issues'
on:
  schedule:
    # Hourly
    - cron: '0 * * * *'
permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'sommerit' }}
    steps:
      - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008
        with:
          any-of-labels: 'solved'
          stale-issue-label: 'solved'
          days-before-stale: 0
          days-before-close: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
