# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[Automation] Label closed items'
on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]
permissions:
  issues: write
  pull-requests: write
jobs:
  label-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'closed' label to issues
        if: ${{ github.event_name == 'issues' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: ['closed']
            });
      - name: Add 'closed' label to PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['closed']
            });
