# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# This is a hack to run reusable workflows in the main repo context and not from the forked repository.
# We this hack we can use secrets configured in the organization.
# NOTE: This workflow is maintained in the https://github.com/bitnami/support repository
name: '[Automation] PR review comment trigger (no-op)'
on:
  workflow_run:
    workflows:
      - '[Automation] PR review labeling'
    types:
      - completed
permissions: {}
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No-op. Upstream reusable workflow replaced."
