# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[Automation] PR review labeling'
on:
  pull_request_review:
    types: [submitted, dismissed]
permissions:
  pull-requests: write
jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Update labels based on review state
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            const state = context.payload.review?.state || '';
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = pr.number;
            if (state.toLowerCase() === 'approved') {
              try { await github.rest.issues.removeLabel({owner, repo, issue_number, name: 'needs-review'}); } catch (e) {}
              await github.rest.issues.addLabels({owner, repo, issue_number, labels: ['approved']});
            } else if (state.toLowerCase() === 'changes_requested') {
              await github.rest.issues.addLabels({owner, repo, issue_number, labels: ['changes-requested']});
            }
