# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[Automation] Review requested labeling'
on:
  pull_request:
    types: [review_requested, synchronize]
permissions:
  pull-requests: write
jobs:
  label-needs-review:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'needs-review' label when review requested
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['needs-review']
            });
