# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# NOTE: This workflow is maintained in the https://github.com/bitnami/support repository
name: '[Automation] Label acknowledgment'
on:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]
permissions:
  issues: write
  pull-requests: write
jobs:
  comment-label:
    runs-on: ubuntu-latest
    steps:
      - name: Comment label notice
        uses: actions/github-script@v7
        with:
          script: |
            const label = context.payload.label?.name;
            if (!label) return;
            const issue_number = (context.payload.issue?.number) || (context.payload.pull_request?.number);
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number, body: `Label added: ${label}` });
