# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

# This workflow is built to manage the triage support by using GH issues.
# NOTE: This workflow is maintained in the https://github.com/bitnami/support repository
name: '[Automation] Triage labels'
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
permissions:
  issues: write
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label new issues
        if: ${{ github.event_name == 'issues' }}
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.issue.number, labels: ['triage'] });
      - name: Label new PRs
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.pull_request.number, labels: ['triage'] });
